[package]
name = "taskTracker"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.133"
tempfile = "3.13.0"
chrono = { version = "0.4", features = ["serde"] }

